# Generated by Django 5.1.2 on 2024-10-31 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=32)),
                ('title_name_en', models.CharField(max_length=32, null=True)),
                ('title_name_ru', models.CharField(max_length=32, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(max_length=10)),
                ('volume', models.PositiveSmallIntegerField(default=0)),
                ('year', models.IntegerField()),
                ('type_change', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='vid/')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=16, null=True)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='shop.marka')),
            ],
        ),
    ]
